development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: myapp_dev
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: myapp_test
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

